FROM ubuntu:22.04

RUN apt-get update && apt-get install -y git openssl

ARG GODOT_VERSION=4.4-stable
ARG GODOT_STEAM_VERSION=godot4

# Clone godot and godotsteam repositories
RUN echo "Cloning Godot repository ..."
RUN git clone -b $GODOT_VERSION https://github.com/godotengine/godot.git /godot_setup/godot
RUN echo "Cloning GodotSteam repository ..."
RUN git clone -b $GODOT_STEAM_VERSION https://github.com/Gramps/GodotSteam.git /godot_setup/godot/modules/godotsteam

# Copy Steam redistributables
COPY steam_sdk/sdk/public /godot_setup/godot/modules/godotsteam/sdk/public
COPY steam_sdk/sdk/redistributable_bin /godot_setup/godot/modules/godotsteam/sdk/redistributable_bin

# Generate encryption key
RUN openssl rand -hex 32 > /godot_setup/godot.gdkey

# Allow the editng of contents
RUN chmod -R a+rw /godot_setup